"""empty message

Revision ID: 4bc6fa0dbaef
Revises: 
Create Date: 2023-05-23 22:44:32.628009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bc6fa0dbaef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('user')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('nunum')

    op.drop_table('document')
    with op.batch_alter_table('jiansuo', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('jiansuo')
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('t2')

    op.drop_table('food')
    op.drop_table('fencifanwei')
    with op.batch_alter_table('fencibiao', schema=None) as batch_op:
        batch_op.drop_index('wnum')

    op.drop_table('fencibiao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fencibiao',
    sa.Column('wnum', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('word', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('fnum', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('wnum'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fencibiao', schema=None) as batch_op:
        batch_op.create_index('wnum', ['wnum'], unique=False)

    op.create_table('fencifanwei',
    sa.Column('word', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('began', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('down', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('food',
    sa.Column('fnum', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type1', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('type2', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('fname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('img', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('energy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('fnum'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index('t2', ['type2'], unique=False)
        batch_op.create_index('id', ['fnum'], unique=False)

    op.create_table('jiansuo',
    sa.Column('jnum', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('jnum'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jiansuo', schema=None) as batch_op:
        batch_op.create_index('id', ['jnum'], unique=False)

    op.create_table('document',
    sa.Column('dnum', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('time', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fnum', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('weight', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unum', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('energy', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('dnum'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('nunum', ['unum'], unique=False)

    op.create_table('user',
    sa.Column('number', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('zhanghao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('number'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('id', ['number'], unique=False)

    # ### end Alembic commands ###
