"""empty message

Revision ID: 79006583bb87
Revises: 87cdf10e692c
Create Date: 2023-05-28 22:16:11.936706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79006583bb87'
down_revision = '87cdf10e692c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('dnum',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('ix_document_dnum')
        batch_op.drop_index('ix_document_unum')
        batch_op.create_index(batch_op.f('ix_document_zhanghao'), ['zhanghao'], unique=False)

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.alter_column('fnum',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('energy',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_food_type1'), ['type1'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_type2'), ['type2'], unique=False)
        batch_op.create_unique_constraint(None, ['fnum'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_food_type2'))
        batch_op.drop_index(batch_op.f('ix_food_type1'))
        batch_op.alter_column('energy',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('fnum',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_zhanghao'))
        batch_op.create_index('ix_document_unum', ['zhanghao'], unique=False)
        batch_op.create_index('ix_document_dnum', ['dnum'], unique=False)
        batch_op.alter_column('weight',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('dnum',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
